import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useConnect } from "wagmi";
import Card from "../components/Card";
import useEnsData from "../hooks/useEnsData";
import styles from "../styles/Home.module.css";
import { ensDataType } from "../types/ensType";

const Home: NextPage = () => {
  const [domainName, setDomainName] = useState("");
  const [finalDomainName, setFinalDomainName] = useState(domainName);
  const [currentAddr, setCurrentAddr] = useState(undefined);
  const [isConnect, setIsConnect] = useState(false);
  const ensData: ensDataType = useEnsData(currentAddr, finalDomainName);
  const { connect, connectors, error, isLoading, pendingConnector, isSuccess } =
    useConnect();

  useEffect(() => {
    if (isSuccess) {
      setCurrentAddr("0x08C5E50244FC58bc15Bf07BDAbb67453e624CB17");
      setFinalDomainName("edhal.ens");
    }
  }, [isSuccess]);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <Card cardData={ensData} cardBgColor={"#cdcdcd"} colors={[]}></Card>
      </main>
    </div>
  );
};

export default Home;
